In [1]:
import pandas as pd

In [3]:
pred=pd.read_csv('preds/fastai0.csv')
for i in [1,6,7,15,42,70,80,96,99,154,482,666,854,123456,123465]:
    p1=pd.read_csv('preds/fastai'+str(i)+'.csv')
    pred=pd.concat([pred,p1],axis=1)
pred

,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture,Culture
0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,12.0,12.0,12.0,12.0,12.0,12.0,13.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
2,12.0,12.0,16.0,7.0,10.0,12.0,16.0,7.0,16.0,16.0,10.0,10.0,16.0,12.0,12.0,10.0
3,7.0,7.0,3.0,3.0,7.0,3.0,3.0,3.0,16.0,7.0,7.0,3.0,7.0,3.0,7.0,3.0
4,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,10.0,10.0,10.0,10.0,10.0,16.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
935,10.0,7.0,7.0,7.0,7.0,19.0,7.0,10.0,7.0,10.0,16.0,10.0,7.0,10.0,10.0,10.0
936,7.0,10.0,7.0,7.0,7.0,3.0,7.0,10.0,7.0,7.0,7.0,7.0,3.0,7.0,7.0,10.0
937,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,14.0,14.0,14.0,12.0,12.0,12.0
938,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

In [4]:
pred.columns=['0','1','6','7','15','42','70','80','96','99','154','482','666','854','123456','123465']

In [5]:
pred

,0,1,6,7,15,42,70,80,96,99,154,482,666,854,123456,123465
0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,12.0,12.0,12.0,12.0,12.0,12.0,13.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
2,12.0,12.0,16.0,7.0,10.0,12.0,16.0,7.0,16.0,16.0,10.0,10.0,16.0,12.0,12.0,10.0
3,7.0,7.0,3.0,3.0,7.0,3.0,3.0,3.0,16.0,7.0,7.0,3.0,7.0,3.0,7.0,3.0
4,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,10.0,10.0,10.0,10.0,10.0,16.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
935,10.0,7.0,7.0,7.0,7.0,19.0,7.0,10.0,7.0,10.0,16.0,10.0,7.0,10.0,10.0,10.0
936,7.0,10.0,7.0,7.0,7.0,3.0,7.0,10.0,7.0,7.0,7.0,7.0,3.0,7.0,7.0,10.0
937,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,14.0,14.0,14.0,12.0,12.0,12.0
938,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

In [22]:
final=[]
for i in range(len(pred.index)):
    final.append(pred.loc[i].value_counts().index.tolist()[0])
    print(pred.loc[i].value_counts())

4.0    16
Name: 0, dtype: int64
12.0    15
13.0     1
Name: 1, dtype: int64
16.0    5
12.0    5
10.0    4
7.0     2
Name: 2, dtype: int64
3.0     8
7.0     7
16.0    1
Name: 3, dtype: int64
4.0    16
Name: 4, dtype: int64
4.0    16
Name: 5, dtype: int64
17.0    5
10.0    4
8.0     4
16.0    2
5.0     1
Name: 6, dtype: int64
5.0    11
8.0     4
4.0     1
Name: 7, dtype: int64
19.0    14
7.0      2
Name: 8, dtype: int64
4.0    16
Name: 9, dtype: int64
4.0    16
Name: 10, dtype: int64
3.0     9
16.0    4
7.0     3
Name: 11, dtype: int64
4.0    16
Name: 12, dtype: int64
9.0     9
5.0     5
14.0    2
Name: 13, dtype: int64
9.0    16
Name: 14, dtype: int64
9.0    15
8.0     1
Name: 15, dtype: int64
4.0    16
Name: 16, dtype: int64
3.0     11
7.0      3
10.0     1
16.0     1
Name: 17, dtype: int64
5.0    8
1.0    7
8.0    1
Name: 18, dtype: int64
4.0    14
3.0     2
Name: 19, dtype: int64
4.0    16
Name: 20, dtype: int64
5.0    12
7.0     3
3.0     1
Name: 21, dtype: int64
3.0    9
4.0    5
7.0    2
Name: 22, dtype: int64
7.0     13
10.0     1
4.0      1
12.0     1
Name: 23, dtype: int64
11.0    14
10.0     1
4.0      1
Name: 24, dtype: int64
4.0    16
Name: 25, dtype: int64
4.0    16
Name: 26, dtype: int64
4.0    12
5.0     4
Name: 27, dtype: int64
4.0    16
Name: 28, dtype: int64
4.0    16
Name: 29, dtype: int64
4.0     15
13.0     1
Name: 30, dtype: int64
7.0    16
Name: 31, dtype: int64
8.0     8
4.0     3
5.0     2
17.0    1
9.0     1
11.0    1
Name: 32, dtype: int64
7.0     12
18.0     4
Name: 33, dtype: int64
3.0    13
7.0     3
Name: 34, dtype: int64
10.0    15
12.0     1
Name: 35, dtype: int64
4.0    16
Name: 36, dtype: int64
7.0     5
4.0     4
3.0     3
13.0    3
11.0    1
Name: 37, dtype: int64
10.0    16
Name: 38, dtype: int64
8.0     8
10.0    3
14.0    2
11.0    2
16.0    1
Name: 39, dtype: int64
14.0    15
7.0      1
Name: 40, dtype: int64
3.0    11
7.0     5
Name: 41, dtype: int64
19.0    13
3.0      3
Name: 42, dtype: int64
4.0    16
Name: 43, dtype: int64
10.0    16
Name: 44, dtype: int64
4.0    13
9.0     3
Name: 45, dtype: int64
4.0    16
Name: 46, dtype: int64
4.0     15
10.0     1
Name: 47, dtype: int64
4.0    12
5.0     4
Name: 48, dtype: int64
4.0    16
Name: 49, dtype: int64
4.0    16
Name: 50, dtype: int64
4.0     15
13.0     1
Name: 51, dtype: int64
10.0    11
11.0     5
Name: 52, dtype: int64
10.0    16
Name: 53, dtype: int64
12.0    9
10.0    4
16.0    3
Name: 54, dtype: int64
5.0     7
4.0     5
16.0    2
19.0    2
Name: 55, dtype: int64
4.0    16
Name: 56, dtype: int64
16.0    9
17.0    4
8.0     2
4.0     1
Name: 57, dtype: int64
7.0    9
3.0    7
Name: 58, dtype: int64
4.0     15
13.0     1
Name: 59, dtype: int64
16.0    8
7.0     7
10.0    1
Name: 60, dtype: int64
7.0    12
3.0     4
Name: 61, dtype: int64
3.0     9
14.0    4
16.0    3
Name: 62, dtype: int64
7.0    16
Name: 63, dtype: int64
8.0    16
Name: 64, dtype: int64
10.0    16
Name: 65, dtype: int64
16.0    5
4.0     4
8.0     3
11.0    2
17.0    1
14.0    1
Name: 66, dtype: int64
19.0    7
7.0     6
10.0    2
3.0     1
Name: 67, dtype: int64
4.0    16
Name: 68, dtype: int64
7.0    16
Name: 69, dtype: int64
4.0    16
Name: 70, dtype: int64
4.0     8
13.0    7
12.0    1
Name: 71, dtype: int64
4.0     13
11.0     2
14.0     1
Name: 72, dtype: int64
4.0    16
Name: 73, dtype: int64
4.0    16
Name: 74, dtype: int64
4.0    16
Name: 75, dtype: int64
4.0     13
11.0     2
9.0      1
Name: 76, dtype: int64
9.0     15
11.0     1
Name: 77, dtype: int64
16.0    11
13.0     4
8.0      1
Name: 78, dtype: int64
4.0     11
13.0     5
Name: 79, dtype: int64
8.0    10
5.0     4
4.0     2
Name: 80, dtype: int64
12.0    10
3.0      4
13.0     2
Name: 81, dtype: int64
4.0    15
8.0     1
Name: 82, dtype: int64
8.0    9
4.0    7
Name: 83, dtype: int64
4.0    16
Name: 84, dtype: int64
4.0    16
Name: 85, dtype: int64
9.0    8
8.0    6
4.0    2
Name: 86, dtype: int64
11.0    12
10.0     2
12.0     1
4.0      1
Name: 87, dtype: int64
4.0    16
Name: 88, dtype: int64
4.0    16
Name: 89, dtype: int64
4.0    16
Name: 90, dtype: int64
8.0    16
Name: 91, dtype: int64
4.0     14
13.0     2
Name: 92, dtype: int64
3.0    9
7.0    7
Name: 93, dtype: int64
4.0    12
8.0     4
Name: 94, dtype: int64
4.0    16
Name: 95, dtype: int64
4.0     8
7.0     4
11.0    4
Name: 96, dtype: int64
9.0     14
14.0     2
Name: 97, dtype: int64
7.0     9
4.0     3
10.0    2
16.0    1
3.0     1
Name: 98, dtype: int64
4.0    16
Name: 99, dtype: int64
4.0    16
Name: 100, dtype: int64
10.0    11
4.0      4
9.0      1
Name: 101, dtype: int64
4.0    16
Name: 102, dtype: int64
10.0    16
Name: 103, dtype: int64
8.0    9
5.0    4
3.0    2
9.0    1
Name: 104, dtype: int64
4.0    16
Name: 105, dtype: int64
4.0     15
13.0     1
Name: 106, dtype: int64
4.0     14
13.0     2
Name: 107, dtype: int64
9.0     5
8.0     4
5.0     3
2.0     1
4.0     1
14.0    1
1.0     1
Name: 108, dtype: int64
4.0    16
Name: 109, dtype: int64
4.0    16
Name: 110, dtype: int64
10.0    11
17.0     4
16.0     1
Name: 111, dtype: int64
4.0    11
9.0     5
Name: 112, dtype: int64
5.0     7
17.0    4
8.0     3
7.0     1
16.0    1
Name: 113, dtype: int64
9.0     14
11.0     2
Name: 114, dtype: int64
4.0    16
Name: 115, dtype: int64
4.0    16
Name: 116, dtype: int64
16.0    9
10.0    7
Name: 117, dtype: int64
4.0     15
13.0     1
Name: 118, dtype: int64
4.0     15
13.0     1
Name: 119, dtype: int64
4.0    16
Name: 120, dtype: int64
4.0    16
Name: 121, dtype: int64
3.0     12
4.0      3
14.0     1
Name: 122, dtype: int64
4.0    16
Name: 123, dtype: int64
9.0    16
Name: 124, dtype: int64
4.0    16
Name: 125, dtype: int64
16.0    16
Name: 126, dtype: int64
12.0    16
Name: 127, dtype: int64
4.0     11
3.0      2
13.0     1
11.0     1
10.0     1
Name: 128, dtype: int64
10.0    15
17.0     1
Name: 129, dtype: int64
16.0    9
4.0     6
17.0    1
Name: 130, dtype: int64
19.0    11
7.0      4
8.0      1
Name: 131, dtype: int64
4.0     13
13.0     3
Name: 132, dtype: int64
11.0    12
4.0      3
8.0      1
Name: 133, dtype: int64
9.0    10
4.0     6
Name: 134, dtype: int64
9.0    16
Name: 135, dtype: int64
4.0    16
Name: 136, dtype: int64
8.0    8
9.0    7
2.0    1
Name: 137, dtype: int64
4.0     13
14.0     2
17.0     1
Name: 138, dtype: int64
16.0    9
4.0     4
13.0    2
3.0     1
Name: 139, dtype: int64
4.0    16
Name: 140, dtype: int64
10.0    9
11.0    2
3.0     2
16.0    1
4.0     1
12.0    1
Name: 141, dtype: int64
7.0     14
10.0     1
3.0      1
Name: 142, dtype: int64
8.0    16
Name: 143, dtype: int64
4.0    16
Name: 144, dtype: int64
10.0    7
7.0     6
5.0     2
4.0     1
Name: 145, dtype: int64
4.0     15
10.0     1
Name: 146, dtype: int64
4.0    8
2.0    5
9.0    3
Name: 147, dtype: int64
9.0    16
Name: 148, dtype: int64
4.0     14
13.0     2
Name: 149, dtype: int64
4.0     9
13.0    7
Name: 150, dtype: int64
4.0    16
Name: 151, dtype: int64
12.0    10
4.0      6
Name: 152, dtype: int64
9.0     11
11.0     5
Name: 153, dtype: int64
4.0     8
10.0    7
11.0    1
Name: 154, dtype: int64
10.0    16
Name: 155, dtype: int64
12.0    14
7.0      2
Name: 156, dtype: int64
4.0    16
Name: 157, dtype: int64
8.0     13
14.0     3
Name: 158, dtype: int64
4.0    11
9.0     5
Name: 159, dtype: int64
4.0     11
10.0     5
Name: 160, dtype: int64
6.0     9
4.0     6
10.0    1
Name: 161, dtype: int64
4.0     11
10.0     4
11.0     1
Name: 162, dtype: int64
4.0    16
Name: 163, dtype: int64
4.0    16
Name: 164, dtype: int64
5.0    13
8.0     3
Name: 165, dtype: int64
10.0    16
Name: 166, dtype: int64
4.0     15
13.0     1
Name: 167, dtype: int64
4.0    16
Name: 168, dtype: int64
4.0    15
3.0     1
Name: 169, dtype: int64
5.0    10
9.0     5
8.0     1
Name: 170, dtype: int64
12.0    16
Name: 171, dtype: int64
10.0    10
16.0     5
3.0      1
Name: 172, dtype: int64
4.0    16
Name: 173, dtype: int64
4.0    16
Name: 174, dtype: int64
4.0    11
9.0     4
8.0     1
Name: 175, dtype: int64
3.0    16
Name: 176, dtype: int64
4.0    16
Name: 177, dtype: int64
4.0    16
Name: 178, dtype: int64
10.0    15
4.0      1
Name: 179, dtype: int64
3.0    16
Name: 180, dtype: int64
4.0    16
Name: 181, dtype: int64
6.0    13
8.0     2
4.0     1
Name: 182, dtype: int64
9.0    16
Name: 183, dtype: int64
4.0    16
Name: 184, dtype: int64
4.0    16
Name: 185, dtype: int64
9.0    16
Name: 186, dtype: int64
4.0    16
Name: 187, dtype: int64
4.0    16
Name: 188, dtype: int64
4.0    16
Name: 189, dtype: int64
4.0    16
Name: 190, dtype: int64
4.0    16
Name: 191, dtype: int64
4.0    16
Name: 192, dtype: int64
3.0    16
Name: 193, dtype: int64
10.0    10
4.0      5
8.0      1
Name: 194, dtype: int64
3.0     6
4.0     4
7.0     4
10.0    1
16.0    1
Name: 195, dtype: int64
16.0    13
3.0      1
20.0     1
14.0     1
Name: 196, dtype: int64
13.0    10
4.0      6
Name: 197, dtype: int64
19.0    16
Name: 198, dtype: int64
5.0    9
4.0    7
Name: 199, dtype: int64
3.0    16
Name: 200, dtype: int64
4.0    16
Name: 201, dtype: int64
9.0    16
Name: 202, dtype: int64
2.0    13
9.0     2
4.0     1
Name: 203, dtype: int64
3.0     6
7.0     6
16.0    4
Name: 204, dtype: int64
4.0    16
Name: 205, dtype: int64
11.0    9
4.0     7
Name: 206, dtype: int64
4.0    16
Name: 207, dtype: int64
4.0    16
Name: 208, dtype: int64
4.0    16
Name: 209, dtype: int64
14.0    11
4.0      5
Name: 210, dtype: int64
4.0    16
Name: 211, dtype: int64
4.0    16
Name: 212, dtype: int64
4.0    12
9.0     4
Name: 213, dtype: int64
4.0     15
13.0     1
Name: 214, dtype: int64
4.0    16
Name: 215, dtype: int64
7.0     11
3.0      3
16.0     2
Name: 216, dtype: int64
3.0     9
10.0    6
7.0     1
Name: 217, dtype: int64
4.0     8
7.0     4
11.0    4
Name: 218, dtype: int64
9.0    16
Name: 219, dtype: int64
4.0    16
Name: 220, dtype: int64
4.0     15
11.0     1
Name: 221, dtype: int64
4.0    16
Name: 222, dtype: int64
3.0     5
5.0     4
19.0    4
7.0     3
Name: 223, dtype: int64
10.0    16
Name: 224, dtype: int64
4.0    16
Name: 225, dtype: int64
5.0    16
Name: 226, dtype: int64
9.0    16

Name: 227, dtype: int64
5.0     8
19.0    3
4.0     2
3.0     2
11.0    1
Name: 228, dtype: int64
4.0    16
Name: 229, dtype: int64
8.0     8
5.0     3
14.0    2
7.0     2
12.0    1
Name: 230, dtype: int64
4.0    16
Name: 231, dtype: int64
4.0    16
Name: 232, dtype: int64
4.0    16
Name: 233, dtype: int64
4.0    16
Name: 234, dtype: int64
4.0    16
Name: 235, dtype: int64
4.0    16
Name: 236, dtype: int64
4.0     15
11.0     1
Name: 237, dtype: int64
8.0    14
7.0     2
Name: 238, dtype: int64
4.0     11
13.0     5
Name: 239, dtype: int64
5.0     8
16.0    5
13.0    1
7.0     1
1.0     1
Name: 240, dtype: int64
13.0    4
10.0    3
8.0     3
4.0     2
16.0    2
3.0     1
7.0     1
Name: 241, dtype: int64
3.0    16
Name: 242, dtype: int64
4.0     11
13.0     5
Name: 243, dtype: int64
4.0    14
8.0     2
Name: 244, dtype: int64
3.0    15
8.0     1
Name: 245, dtype: int64
4.0     14
13.0     2
Name: 246, dtype: int64
12.0    14
17.0     2
Name: 247, dtype: int64
4.0    16
Name: 248, dtype: int64
11.0    11
4.0      3
10.0     2
Name: 249, dtype: int64
4.0     10
21.0     3
11.0     2
10.0     1
Name: 250, dtype: int64
11.0    8
4.0     7
14.0    1
Name: 251, dtype: int64
4.0     15
13.0     1
Name: 252, dtype: int64
10.0    16
Name: 253, dtype: int64
21.0    7
10.0    4
4.0     3
7.0     1
11.0    1
Name: 254, dtype: int64
4.0    16
Name: 255, dtype: int64
4.0    16
Name: 256, dtype: int64
7.0     9
12.0    6
13.0    1
Name: 257, dtype: int64
3.0     14
8.0      1
10.0     1
Name: 258, dtype: int64
4.0    16
Name: 259, dtype: int64
10.0    11
7.0      2
16.0     2
19.0     1
Name: 260, dtype: int64
10.0    14
16.0     2
Name: 261, dtype: int64
14.0    16
Name: 262, dtype: int64
12.0    15
14.0     1
Name: 263, dtype: int64
4.0    16
Name: 264, dtype: int64
4.0    16
Name: 265, dtype: int64
4.0    16
Name: 266, dtype: int64
4.0     8
10.0    8
Name: 267, dtype: int64
4.0     12
12.0     2
13.0     2
Name: 268, dtype: int64
9.0    16
Name: 269, dtype: int64
9.0    16
Name: 270, dtype: int64
7.0    16
Name: 271, dtype: int64
9.0    10
8.0     4
2.0     2
Name: 272, dtype: int64
16.0    9
3.0     7
Name: 273, dtype: int64
4.0    16
Name: 274, dtype: int64
9.0     13
4.0      2
13.0     1
Name: 275, dtype: int64
7.0     7
3.0     5
16.0    4
Name: 276, dtype: int64
10.0    11
4.0      5
Name: 277, dtype: int64
17.0    7
12.0    7
10.0    2
Name: 278, dtype: int64
3.0    9
7.0    3
8.0    2
5.0    2
Name: 279, dtype: int64
5.0     7
16.0    7
10.0    2
Name: 280, dtype: int64
12.0    13
10.0     2
13.0     1
Name: 281, dtype: int64
9.0    16
Name: 282, dtype: int64
17.0    9
12.0    7
Name: 283, dtype: int64
16.0    10
7.0      6
Name: 284, dtype: int64
4.0    16
Name: 285, dtype: int64
4.0    16
Name: 286, dtype: int64
4.0    16
Name: 287, dtype: int64
13.0    9
4.0     7
Name: 288, dtype: int64
4.0    16
Name: 289, dtype: int64
4.0    16
Name: 290, dtype: int64
10.0    10
12.0     5
7.0      1
Name: 291, dtype: int64
4.0    16
Name: 292, dtype: int64
17.0    14
12.0     2
Name: 293, dtype: int64
14.0    13
4.0      3
Name: 294, dtype: int64
4.0    16
Name: 295, dtype: int64
10.0    16
Name: 296, dtype: int64
10.0    13
4.0      3
Name: 297, dtype: int64
4.0    16
Name: 298, dtype: int64
4.0    16
Name: 299, dtype: int64
4.0    16
Name: 300, dtype: int64
4.0    16
Name: 301, dtype: int64
7.0     11
10.0     4
8.0      1
Name: 302, dtype: int64
4.0    16
Name: 303, dtype: int64
16.0    10
12.0     5
10.0     1
Name: 304, dtype: int64
4.0     10
19.0     3
7.0      2
3.0      1
Name: 305, dtype: int64
4.0     5
9.0     4
11.0    4
14.0    1
19.0    1
5.0     1
Name: 306, dtype: int64
4.0     15
10.0     1
Name: 307, dtype: int64
1.0    8
9.0    7
8.0    1
Name: 308, dtype: int64
3.0    9
7.0    6
8.0    1
Name: 309, dtype: int64
4.0     11
3.0      3
14.0     1
8.0      1
Name: 310, dtype: int64
4.0    16
Name: 311, dtype: int64
5.0    13
9.0     3
Name: 312, dtype: int64
3.0    16
Name: 313, dtype: int64
9.0    16
Name: 314, dtype: int64
10.0    15
17.0     1
Name: 315, dtype: int64
10.0    13
4.0      2
17.0     1
Name: 316, dtype: int64
10.0    7
4.0     4
8.0     3
9.0     1
11.0    1
Name: 317, dtype: int64
4.0    16
Name: 318, dtype: int64
9.0    14
8.0     2
Name: 319, dtype: int64
4.0    16
Name: 320, dtype: int64
9.0    16
Name: 321, dtype: int64
4.0    16
Name: 322, dtype: int64
16.0    8
10.0    5
3.0     2
7.0     1
Name: 323, dtype: int64
3.0    12
8.0     3
7.0     1
Name: 324, dtype: int64
9.0    16
Name: 325, dtype: int64
10.0    16
Name: 326, dtype: int64
4.0    16
Name: 327, dtype: int64
4.0     14
13.0     2
Name: 328, dtype: int64
17.0    7
14.0    6
4.0     3
Name: 329, dtype: int64
4.0    16
Name: 330, dtype: int64
4.0    16
Name: 331, dtype: int64
7.0     8
8.0     5
16.0    3
Name: 332, dtype: int64
4.0    14
5.0     2
Name: 333, dtype: int64
4.0    16
Name: 334, dtype: int64
4.0    8
8.0    7
5.0    1
Name: 335, dtype: int64
8.0     7
22.0    4
5.0     4
4.0     1
Name: 336, dtype: int64
9.0    14
4.0     2
Name: 337, dtype: int64
12.0    5
10.0    5
21.0    5
16.0    1
Name: 338, dtype: int64
4.0    11
8.0     4
5.0     1
Name: 339, dtype: int64
4.0    16
Name: 340, dtype: int64
4.0     13
13.0     3
Name: 341, dtype: int64
14.0    9
2.0     4
9.0     3
Name: 342, dtype: int64
11.0    8
17.0    7
12.0    1
Name: 343, dtype: int64
4.0    10
9.0     4
8.0     2
Name: 344, dtype: int64
7.0    15
3.0     1
Name: 345, dtype: int64
4.0     14
17.0     2
Name: 346, dtype: int64
5.0    7
4.0    7
8.0    2
Name: 347, dtype: int64
10.0    15
17.0     1
Name: 348, dtype: int64
4.0     15
13.0     1
Name: 349, dtype: int64
4.0    16
Name: 350, dtype: int64
4.0     15
13.0     1
Name: 351, dtype: int64
4.0    16
Name: 352, dtype: int64
4.0     9
11.0    6
7.0     1
Name: 353, dtype: int64
4.0    16
Name: 354, dtype: int64
12.0    16
Name: 355, dtype: int64
4.0     15
13.0     1
Name: 356, dtype: int64
4.0    16
Name: 357, dtype: int64
4.0    9
8.0    6
9.0    1
Name: 358, dtype: int64
4.0     11
13.0     5
Name: 359, dtype: int64
16.0    9
4.0     4
5.0     1
15.0    1
7.0     1
Name: 360, dtype: int64
7.0     8
16.0    4
10.0    4
Name: 361, dtype: int64
10.0    7
11.0    5
3.0     3
4.0     1
Name: 362, dtype: int64
4.0     13
13.0     3
Name: 363, dtype: int64
4.0     9
3.0     3
14.0    2
8.0     2
Name: 364, dtype: int64
4.0     13
13.0     3
Name: 365, dtype: int64
4.0    16
Name: 366, dtype: int64
4.0    16
Name: 367, dtype: int64
5.0    12
4.0     4
Name: 368, dtype: int64
7.0     9
4.0     4
14.0    1
9.0     1
13.0    1
Name: 369, dtype: int64
4.0     15
13.0     1
Name: 370, dtype: int64
16.0    16
Name: 371, dtype: int64
3.0     10
7.0      5
10.0     1
Name: 372, dtype: int64
4.0    16
Name: 373, dtype: int64
3.0    12
7.0     4
Name: 374, dtype: int64
8.0     6
9.0     4
15.0    4
4.0     2
Name: 375, dtype: int64
19.0    11
7.0      3
3.0      2
Name: 376, dtype: int64
4.0     9
13.0    5
12.0    2
Name: 377, dtype: int64
9.0    16
Name: 378, dtype: int64
16.0    16
Name: 379, dtype: int64
4.0    16
Name: 380, dtype: int64
4.0    16
Name: 381, dtype: int64
4.0     14
14.0     2
Name: 382, dtype: int64
4.0    16
Name: 383, dtype: int64
4.0     15
13.0     1
Name: 384, dtype: int64
5.0    13
8.0     2
4.0     1
Name: 385, dtype: int64
4.0    16
Name: 386, dtype: int64
14.0    8
3.0     5
8.0     1
11.0    1
7.0     1
Name: 387, dtype: int64
5.0    16
Name: 388, dtype: int64
9.0    16
Name: 389, dtype: int64
10.0    12
3.0      3
12.0     1
Name: 390, dtype: int64
4.0    16
Name: 391, dtype: int64
16.0    7
4.0     5
10.0    3
5.0     1
Name: 392, dtype: int64
4.0     9
13.0    7
Name: 393, dtype: int64
3.0     5
16.0    4
10.0    3
19.0    2
12.0    1
7.0     1
Name: 394, dtype: int64
4.0     14
11.0     1
10.0     1
Name: 395, dtype: int64
9.0    16
Name: 396, dtype: int64
4.0    16
Name: 397, dtype: int64
5.0    12
8.0     4
Name: 398, dtype: int64
4.0    15
5.0     1
Name: 399, dtype: int64
4.0    16
Name: 400, dtype: int64
9.0    16
Name: 401, dtype: int64
10.0    8
16.0    7
19.0    1
Name: 402, dtype: int64
4.0    16
Name: 403, dtype: int64
7.0     15
13.0     1
Name: 404, dtype: int64
4.0     10
10.0     6
Name: 405, dtype: int64
10.0    12
4.0      4
Name: 406, dtype: int64
4.0    16
Name: 407, dtype: int64
4.0     13
10.0     3
Name: 408, dtype: int64
14.0    10
9.0      3
2.0      3
Name: 409, dtype: int64
4.0     15
10.0     1
Name: 410, dtype: int64
3.0     11
14.0     3
7.0      2
Name: 411, dtype: int64
3.0    16
Name: 412, dtype: int64
4.0    16
Name: 413, dtype: int64
14.0    12
4.0      3
9.0      1
Name: 414, dtype: int64
4.0    16
Name: 415, dtype: int64
8.0    16
Name: 416, dtype: int64
4.0    16
Name: 417, dtype: int64
4.0    15
7.0     1
Name: 418, dtype: int64
4.0    16
Name: 419, dtype: int64
4.0    16

Name: 420, dtype: int64
10.0    11
3.0      2
2.0      2
21.0     1
Name: 421, dtype: int64
7.0    11
5.0     5
Name: 422, dtype: int64
12.0    16
Name: 423, dtype: int64
10.0    14
17.0     2
Name: 424, dtype: int64
4.0    16
Name: 425, dtype: int64
4.0    16
Name: 426, dtype: int64
4.0    9
8.0    7
Name: 427, dtype: int64
5.0    16
Name: 428, dtype: int64
4.0    13
8.0     3
Name: 429, dtype: int64
4.0    16
Name: 430, dtype: int64
9.0    16
Name: 431, dtype: int64
10.0    16
Name: 432, dtype: int64
16.0    7
10.0    6
7.0     3
Name: 433, dtype: int64
7.0    16
Name: 434, dtype: int64
3.0     14
7.0      1
16.0     1
Name: 435, dtype: int64
9.0    14
4.0     2
Name: 436, dtype: int64
13.0    8
4.0     8
Name: 437, dtype: int64
4.0    15
9.0     1
Name: 438, dtype: int64
3.0    14
7.0     2
Name: 439, dtype: int64
4.0    16
Name: 440, dtype: int64
3.0    16
Name: 441, dtype: int64
4.0     15
10.0     1
Name: 442, dtype: int64
4.0     10
13.0     4
10.0     2
Name: 443, dtype: int64
2.0     12
10.0     2
9.0      1
7.0      1
Name: 444, dtype: int64
4.0    16
Name: 445, dtype: int64
4.0    16
Name: 446, dtype: int64
8.0    9
4.0    6
7.0    1
Name: 447, dtype: int64
4.0    11
9.0     5
Name: 448, dtype: int64
10.0    11
9.0      4
4.0      1
Name: 449, dtype: int64
4.0     13
13.0     3
Name: 450, dtype: int64
4.0    16
Name: 451, dtype: int64
4.0    16
Name: 452, dtype: int64
4.0     15
13.0     1
Name: 453, dtype: int64
4.0     6
7.0     3
17.0    2
16.0    2
5.0     1
10.0    1
3.0     1
Name: 454, dtype: int64
3.0     8
7.0     6
10.0    1
4.0     1
Name: 455, dtype: int64
8.0    13
5.0     3
Name: 456, dtype: int64
11.0    12
10.0     4
Name: 457, dtype: int64
10.0    11
4.0      2
7.0      2
16.0     1
Name: 458, dtype: int64
4.0    16
Name: 459, dtype: int64
16.0    13
3.0      3
Name: 460, dtype: int64
10.0    16
Name: 461, dtype: int64
9.0     12
8.0      3
14.0     1
Name: 462, dtype: int64
16.0    14
10.0     1
3.0      1
Name: 463, dtype: int64
4.0     13
9.0      2
10.0     1
Name: 464, dtype: int64
4.0    16
Name: 465, dtype: int64
4.0    16
Name: 466, dtype: int64
4.0    16
Name: 467, dtype: int64
4.0    11
8.0     5
Name: 468, dtype: int64
4.0     11
5.0      4
17.0     1
Name: 469, dtype: int64
9.0    13
7.0     2
1.0     1
Name: 470, dtype: int64
4.0     11
13.0     5
Name: 471, dtype: int64
4.0    16
Name: 472, dtype: int64
10.0    7
2.0     6
5.0     2
21.0    1
Name: 473, dtype: int64
7.0     12
16.0     3
3.0      1
Name: 474, dtype: int64
4.0    16
Name: 475, dtype: int64
5.0     7
16.0    6
3.0     1
12.0    1
10.0    1
Name: 476, dtype: int64
5.0     8
12.0    2
9.0     2
11.0    2
16.0    1
8.0     1
Name: 477, dtype: int64
10.0    11
4.0      5
Name: 478, dtype: int64
4.0     13
13.0     3
Name: 479, dtype: int64
4.0    16
Name: 480, dtype: int64
9.0    16
Name: 481, dtype: int64
7.0     14
19.0     1
8.0      1
Name: 482, dtype: int64
4.0    14
5.0     2
Name: 483, dtype: int64
4.0     13
13.0     3
Name: 484, dtype: int64
7.0     12
3.0      2
21.0     2
Name: 485, dtype: int64
3.0    15
7.0     1
Name: 486, dtype: int64
8.0    10
4.0     6
Name: 487, dtype: int64
3.0    9
4.0    7
Name: 488, dtype: int64
9.0     8
7.0     6
21.0    1
14.0    1
Name: 489, dtype: int64
10.0    16
Name: 490, dtype: int64
10.0    8
16.0    8
Name: 491, dtype: int64
4.0    14
8.0     2
Name: 492, dtype: int64
4.0    16
Name: 493, dtype: int64
16.0    9
3.0     5
8.0     1
7.0     1
Name: 494, dtype: int64
4.0    16
Name: 495, dtype: int64
4.0    14
8.0     2
Name: 496, dtype: int64
7.0    13
8.0     2
3.0     1
Name: 497, dtype: int64
16.0    12
3.0      4
Name: 498, dtype: int64
4.0    16
Name: 499, dtype: int64
10.0    13
2.0      1
4.0      1
11.0     1
Name: 500, dtype: int64
5.0     9
8.0     5
13.0    2
Name: 501, dtype: int64
3.0    8
7.0    8
Name: 502, dtype: int64
4.0    16
Name: 503, dtype: int64
12.0    14
13.0     1
16.0     1
Name: 504, dtype: int64
8.0    11
7.0     4
4.0     1
Name: 505, dtype: int64
4.0    16
Name: 506, dtype: int64
4.0     14
13.0     1
10.0     1
Name: 507, dtype: int64
4.0    16
Name: 508, dtype: int64
4.0     8
13.0    3
7.0     3
12.0    1
11.0    1
Name: 509, dtype: int64
2.0    7
9.0    4
7.0    4
3.0    1
Name: 510, dtype: int64
13.0    9
4.0     7
Name: 511, dtype: int64
5.0    8
4.0    7
8.0    1
Name: 512, dtype: int64
4.0    16
Name: 513, dtype: int64
5.0    9
4.0    7
Name: 514, dtype: int64
4.0    16
Name: 515, dtype: int64
8.0     9
19.0    4
7.0     3
Name: 516, dtype: int64
9.0    16
Name: 517, dtype: int64
12.0    14
10.0     1
16.0     1
Name: 518, dtype: int64
10.0    8
7.0     5
16.0    2
12.0    1
Name: 519, dtype: int64
8.0    10
4.0     6
Name: 520, dtype: int64
9.0    16
Name: 521, dtype: int64
4.0     15
13.0     1
Name: 522, dtype: int64
10.0    7
4.0     7
18.0    2
Name: 523, dtype: int64
3.0    15
7.0     1
Name: 524, dtype: int64
5.0     10
4.0      5
19.0     1
Name: 525, dtype: int64
7.0     7
10.0    4
16.0    3
21.0    1
3.0     1
Name: 526, dtype: int64
4.0     15
12.0     1
Name: 527, dtype: int64
4.0    16
Name: 528, dtype: int64
4.0    16
Name: 529, dtype: int64
5.0    8
4.0    8
Name: 530, dtype: int64
5.0    6
8.0    6
4.0    3
9.0    1
Name: 531, dtype: int64
4.0    16
Name: 532, dtype: int64
7.0     7
8.0     3
3.0     3
4.0     2
10.0    1
Name: 533, dtype: int64
4.0    16
Name: 534, dtype: int64
10.0    16
Name: 535, dtype: int64
4.0     13
13.0     3
Name: 536, dtype: int64
5.0    12
4.0     3
9.0     1
Name: 537, dtype: int64
4.0    16
Name: 538, dtype: int64
4.0     9
10.0    7
Name: 539, dtype: int64
4.0    16
Name: 540, dtype: int64
4.0    16
Name: 541, dtype: int64
4.0     10
3.0      3
14.0     2
10.0     1
Name: 542, dtype: int64
4.0     11
8.0      4
14.0     1
Name: 543, dtype: int64
19.0    16
Name: 544, dtype: int64
3.0    9
7.0    6
1.0    1
Name: 545, dtype: int64
14.0    14
4.0      2
Name: 546, dtype: int64
19.0    15
10.0     1
Name: 547, dtype: int64
3.0     11
12.0     3
7.0      1
10.0     1
Name: 548, dtype: int64
11.0    9
3.0     5
10.0    1
12.0    1
Name: 549, dtype: int64
4.0    16
Name: 550, dtype: int64
9.0    16
Name: 551, dtype: int64
4.0    16
Name: 552, dtype: int64
4.0    16
Name: 553, dtype: int64
4.0    9
3.0    5
8.0    1
7.0    1
Name: 554, dtype: int64
10.0    15
12.0     1
Name: 555, dtype: int64
8.0    12
4.0     4
Name: 556, dtype: int64
3.0    13
7.0     3
Name: 557, dtype: int64
10.0    12
16.0     3
7.0      1
Name: 558, dtype: int64
19.0    11
16.0     3
4.0      2
Name: 559, dtype: int64
17.0    11
12.0     5
Name: 560, dtype: int64
4.0    16
Name: 561, dtype: int64
14.0    10
9.0      5
2.0      1
Name: 562, dtype: int64
12.0    16
Name: 563, dtype: int64
10.0    16
Name: 564, dtype: int64
3.0    16
Name: 565, dtype: int64
16.0    14
19.0     2
Name: 566, dtype: int64
11.0    13
4.0      2
10.0     1
Name: 567, dtype: int64
4.0    16
Name: 568, dtype: int64
4.0    15
9.0     1
Name: 569, dtype: int64
4.0    15
5.0     1
Name: 570, dtype: int64
4.0    16
Name: 571, dtype: int64
4.0    16
Name: 572, dtype: int64
4.0    16
Name: 573, dtype: int64
4.0     15
17.0     1
Name: 574, dtype: int64
4.0    16
Name: 575, dtype: int64
4.0    16
Name: 576, dtype: int64
4.0     14
13.0     2
Name: 577, dtype: int64
4.0    16
Name: 578, dtype: int64
4.0     13
13.0     3
Name: 579, dtype: int64
3.0     14
10.0     1
4.0      1
Name: 580, dtype: int64
4.0     14
11.0     1
10.0     1
Name: 581, dtype: int64
9.0    16
Name: 582, dtype: int64
3.0    10
4.0     3
7.0     2
5.0     1
Name: 583, dtype: int64
16.0    15
10.0     1
Name: 584, dtype: int64
5.0    12
8.0     3
4.0     1
Name: 585, dtype: int64
4.0    16
Name: 586, dtype: int64
4.0    16
Name: 587, dtype: int64
5.0    13
7.0     3
Name: 588, dtype: int64
3.0    10
4.0     3
7.0     3
Name: 589, dtype: int64
10.0    12
4.0      2
11.0     2
Name: 590, dtype: int64
7.0     8
5.0     5
4.0     2
16.0    1
Name: 591, dtype: int64
10.0    16
Name: 592, dtype: int64
3.0    10
8.0     3
7.0     2
1.0     1
Name: 593, dtype: int64
10.0    15
12.0     1
Name: 594, dtype: int64
3.0    16
Name: 595, dtype: int64
4.0     15
19.0     1
Name: 596, dtype: int64
4.0     8
8.0     7
10.0    1
Name: 597, dtype: int64
9.0    16
Name: 598, dtype: int64
4.0    14
9.0     2
Name: 599, dtype: int64
4.0    16
Name: 600, dtype: int64
4.0    12
8.0     4
Name: 601, dtype: int64
4.0    16
Name: 602, dtype: int64
11.0    9
4.0     7
Name: 603, dtype: int64
4.0    16
Name: 604, dtype: int64
4.0     15
13.0     1
Name: 605, dtype: int64
9.0     15
11.0     1
Name: 606, dtype: int64
4.0     14
13.0     2
Name: 607, dtype: int64
4.0     11
13.0     5
Name: 608, dtype: int64
4.0     13
14.0     3
Name: 609, dtype: int64
4.0    16
Name: 610, dtype: int64
4.0    16
Name: 611, dtype: int64
4.0    16
Name: 612, dtype: int64
4.0    16
Name: 613, dtype: int64
4.0    16
Name: 614, dtype: int64
4.0    16
Name: 615, dtype: int64
4.0     15
11.0     1
Name: 616, dtype: int64
4.0    16
Name: 617, dtype: int64
7.0    13
3.0     3
Name: 618, dtype: int64
4.0    16
Name: 619, dtype: int64
4.0    16
Name: 620, dtype: int64
16.0    8
7.0     4
8.0     4
Name: 621, dtype: int64
9.0    7
5.0    5
8.0    2
4.0    1
2.0    1
Name: 622, dtype: int64
4.0    16
Name: 623, dtype: int64
4.0    16
Name: 624, dtype: int64
14.0    5
3.0     5
7.0     2
15.0    2
8.0     1
16.0    1
Name: 625, dtype: int64
4.0    16
Name: 626, dtype: int64
4.0    16
Name: 627, dtype: int64
4.0    16
Name: 628, dtype: int64
4.0    16
Name: 629, dtype: int64
4.0    16
Name: 630, dtype: int64
8.0     11
4.0      4
21.0     1
Name: 631, dtype: int64
8.0    12
4.0     3
7.0     1
Name: 632, dtype: int64
7.0    9
3.0    7
Name: 633, dtype: int64
4.0     13
19.0     3
Name: 634, dtype: int64
4.0     15
17.0     1
Name: 635, dtype: int64
4.0     9
12.0    5
13.0    1
10.0    1
Name: 636, dtype: int64
16.0    8
12.0    6
13.0    1
10.0    1
Name: 637, dtype: int64
4.0    16
Name: 638, dtype: int64
7.0    13
5.0     1
8.0     1
3.0     1
Name: 639, dtype: int64

4.0    12
9.0     4
Name: 640, dtype: int64
12.0    12
4.0      3
11.0     1
Name: 641, dtype: int64
3.0     11
14.0     2
16.0     1
4.0      1
7.0      1
Name: 642, dtype: int64
4.0    16
Name: 643, dtype: int64
4.0    16
Name: 644, dtype: int64
4.0    16
Name: 645, dtype: int64
7.0     7
4.0     7
11.0    2
Name: 646, dtype: int64
4.0    16
Name: 647, dtype: int64
14.0    14
4.0      2
Name: 648, dtype: int64
10.0    16
Name: 649, dtype: int64
16.0    16
Name: 650, dtype: int64
10.0    13
21.0     3
Name: 651, dtype: int64
9.0    16
Name: 652, dtype: int64
10.0    15
16.0     1
Name: 653, dtype: int64
4.0     15
13.0     1
Name: 654, dtype: int64
4.0    14
5.0     2
Name: 655, dtype: int64
4.0    16
Name: 656, dtype: int64
4.0     15
14.0     1
Name: 657, dtype: int64
4.0     8
11.0    8
Name: 658, dtype: int64
4.0    16
Name: 659, dtype: int64
7.0    11
5.0     3
4.0     2
Name: 660, dtype: int64
4.0    16
Name: 661, dtype: int64
4.0     14
13.0     1
10.0     1
Name: 662, dtype: int64
4.0    16
Name: 663, dtype: int64
16.0    15
8.0      1
Name: 664, dtype: int64
19.0    11
7.0      5
Name: 665, dtype: int64
4.0     12
11.0     3
10.0     1
Name: 666, dtype: int64
4.0     8
13.0    6
12.0    1
10.0    1
Name: 667, dtype: int64
4.0    16
Name: 668, dtype: int64
4.0    16
Name: 669, dtype: int64
3.0    10
8.0     3
4.0     3
Name: 670, dtype: int64
4.0     12
13.0     2
11.0     1
12.0     1
Name: 671, dtype: int64
4.0     10
13.0     5
12.0     1
Name: 672, dtype: int64
4.0     6
13.0    5
12.0    4
10.0    1
Name: 673, dtype: int64
4.0    16
Name: 674, dtype: int64
4.0    7
5.0    7
8.0    2
Name: 675, dtype: int64
4.0    16
Name: 676, dtype: int64
4.0     14
13.0     2
Name: 677, dtype: int64
9.0     15
14.0     1
Name: 678, dtype: int64
4.0    16
Name: 679, dtype: int64
10.0    16
Name: 680, dtype: int64
9.0    9
1.0    5
4.0    1
8.0    1
Name: 681, dtype: int64
4.0    16
Name: 682, dtype: int64
4.0     15
11.0     1
Name: 683, dtype: int64
3.0    16
Name: 684, dtype: int64
4.0    16
Name: 685, dtype: int64
9.0     10
11.0     5
4.0      1
Name: 686, dtype: int64
4.0     15
13.0     1
Name: 687, dtype: int64
4.0     15
12.0     1
Name: 688, dtype: int64
4.0     15
13.0     1
Name: 689, dtype: int64
12.0    15
14.0     1
Name: 690, dtype: int64
4.0    16
Name: 691, dtype: int64
9.0    16
Name: 692, dtype: int64
4.0    16
Name: 693, dtype: int64
4.0     15
13.0     1
Name: 694, dtype: int64
4.0    16
Name: 695, dtype: int64
2.0     8
5.0     3
4.0     2
9.0     1
11.0    1
17.0    1
Name: 696, dtype: int64
4.0    16
Name: 697, dtype: int64
7.0     12
21.0     3
17.0     1
Name: 698, dtype: int64
4.0     12
13.0     4
Name: 699, dtype: int64
5.0    8
4.0    8
Name: 700, dtype: int64
4.0     15
13.0     1
Name: 701, dtype: int64
10.0    16
Name: 702, dtype: int64
4.0    8
9.0    7
5.0    1
Name: 703, dtype: int64
4.0     13
13.0     3
Name: 704, dtype: int64
4.0     10
13.0     6
Name: 705, dtype: int64
4.0     11
11.0     4
8.0      1
Name: 706, dtype: int64
4.0     15
13.0     1
Name: 707, dtype: int64
9.0    16
Name: 708, dtype: int64
4.0    16
Name: 709, dtype: int64
4.0    8
3.0    4
8.0    2
5.0    1
7.0    1
Name: 710, dtype: int64
4.0    16
Name: 711, dtype: int64
16.0    9
19.0    5
3.0     1
7.0     1
Name: 712, dtype: int64
8.0    7
6.0    6
5.0    2
7.0    1
Name: 713, dtype: int64
4.0    16
Name: 714, dtype: int64
12.0    4
7.0     4
4.0     3
13.0    3
11.0    2
Name: 715, dtype: int64
8.0     12
7.0      2
14.0     1
1.0      1
Name: 716, dtype: int64
9.0    15
4.0     1
Name: 717, dtype: int64
4.0    15
5.0     1
Name: 718, dtype: int64
4.0    16
Name: 719, dtype: int64
7.0    16
Name: 720, dtype: int64
4.0     14
10.0     2
Name: 721, dtype: int64
4.0     12
10.0     2
13.0     1
7.0      1
Name: 722, dtype: int64
4.0     13
16.0     2
14.0     1
Name: 723, dtype: int64
4.0    16
Name: 724, dtype: int64
4.0     15
10.0     1
Name: 725, dtype: int64
4.0     10
10.0     3
12.0     2
5.0      1
Name: 726, dtype: int64
4.0    16
Name: 727, dtype: int64
4.0     14
12.0     1
10.0     1
Name: 728, dtype: int64
5.0     13
19.0     3
Name: 729, dtype: int64
3.0     8
10.0    7
7.0     1
Name: 730, dtype: int64
9.0    16
Name: 731, dtype: int64
3.0    15
7.0     1
Name: 732, dtype: int64
4.0    16
Name: 733, dtype: int64
4.0    16
Name: 734, dtype: int64
4.0    16
Name: 735, dtype: int64
13.0    8
4.0     8
Name: 736, dtype: int64
14.0    12
4.0      3
13.0     1
Name: 737, dtype: int64
4.0    16
Name: 738, dtype: int64
19.0    15
7.0      1
Name: 739, dtype: int64
3.0    9
7.0    7
Name: 740, dtype: int64
4.0    16
Name: 741, dtype: int64
4.0    16
Name: 742, dtype: int64
16.0    9
7.0     6
10.0    1
Name: 743, dtype: int64
4.0     11
13.0     5
Name: 744, dtype: int64
4.0     15
13.0     1
Name: 745, dtype: int64
14.0    15
12.0     1
Name: 746, dtype: int64
4.0     15
13.0     1
Name: 747, dtype: int64
9.0    16
Name: 748, dtype: int64
10.0    9
16.0    4
5.0     3
Name: 749, dtype: int64
4.0    16
Name: 750, dtype: int64
10.0    13
21.0     3
Name: 751, dtype: int64
10.0    16
Name: 752, dtype: int64
4.0    16
Name: 753, dtype: int64
19.0    8
5.0     6
8.0     2
Name: 754, dtype: int64
10.0    14
16.0     1
3.0      1
Name: 755, dtype: int64
4.0    16
Name: 756, dtype: int64
4.0    16
Name: 757, dtype: int64
9.0    16
Name: 758, dtype: int64
14.0    16
Name: 759, dtype: int64
16.0    14
10.0     2
Name: 760, dtype: int64
4.0     15
13.0     1
Name: 761, dtype: int64
16.0    13
10.0     2
3.0      1
Name: 762, dtype: int64
3.0    13
7.0     3
Name: 763, dtype: int64
10.0    15
12.0     1
Name: 764, dtype: int64
4.0    16
Name: 765, dtype: int64
4.0    11
8.0     5
Name: 766, dtype: int64
4.0    16
Name: 767, dtype: int64
3.0    16
Name: 768, dtype: int64
22.0    13
11.0     1
10.0     1
9.0      1
Name: 769, dtype: int64
16.0    15
3.0      1
Name: 770, dtype: int64
2.0     7
7.0     5
4.0     3
14.0    1
Name: 771, dtype: int64
4.0     8
13.0    6
12.0    2
Name: 772, dtype: int64
4.0    16
Name: 773, dtype: int64
4.0     15
13.0     1
Name: 774, dtype: int64
4.0    16
Name: 775, dtype: int64
4.0     9
16.0    3
17.0    2
10.0    2
Name: 776, dtype: int64
12.0    16
Name: 777, dtype: int64
4.0     9
10.0    4
11.0    3
Name: 778, dtype: int64
16.0    6
7.0     5
8.0     2
10.0    2
5.0     1
Name: 779, dtype: int64
4.0    16
Name: 780, dtype: int64
14.0    10
17.0     3
4.0      3
Name: 781, dtype: int64
3.0     14
8.0      1
14.0     1
Name: 782, dtype: int64
4.0     8
8.0     5
5.0     2
10.0    1
Name: 783, dtype: int64
9.0     11
8.0      4
14.0     1
Name: 784, dtype: int64
3.0     9
7.0     5
16.0    1
8.0     1
Name: 785, dtype: int64
4.0     14
5.0      1
10.0     1
Name: 786, dtype: int64
9.0    16
Name: 787, dtype: int64
8.0     13
19.0     2
7.0      1
Name: 788, dtype: int64
4.0    15
9.0     1
Name: 789, dtype: int64
4.0    13
8.0     3
Name: 790, dtype: int64
4.0    16
Name: 791, dtype: int64
4.0    16
Name: 792, dtype: int64
9.0    16
Name: 793, dtype: int64
10.0    16
Name: 794, dtype: int64
9.0    16
Name: 795, dtype: int64
4.0    16
Name: 796, dtype: int64
4.0    12
5.0     4
Name: 797, dtype: int64
4.0    16
Name: 798, dtype: int64
4.0    16
Name: 799, dtype: int64
4.0     8
10.0    8
Name: 800, dtype: int64
4.0    16
Name: 801, dtype: int64
10.0    11
4.0      4
13.0     1
Name: 802, dtype: int64
4.0    16
Name: 803, dtype: int64
3.0    16
Name: 804, dtype: int64
4.0    16
Name: 805, dtype: int64
16.0    9
8.0     6
17.0    1
Name: 806, dtype: int64
8.0    13
2.0     2
7.0     1
Name: 807, dtype: int64
4.0     15
13.0     1
Name: 808, dtype: int64
7.0    16
Name: 809, dtype: int64
5.0     6
8.0     5
4.0     4
10.0    1
Name: 810, dtype: int64
4.0    16
Name: 811, dtype: int64
4.0     9
11.0    3
13.0    2
7.0     2
Name: 812, dtype: int64
19.0    11
18.0     3
5.0      1
16.0     1
Name: 813, dtype: int64
4.0    16
Name: 814, dtype: int64
3.0     13
10.0     1
8.0      1
7.0      1
Name: 815, dtype: int64
3.0    16
Name: 816, dtype: int64
16.0    9
7.0     6
3.0     1
Name: 817, dtype: int64
4.0     14
10.0     2
Name: 818, dtype: int64
4.0    16
Name: 819, dtype: int64
10.0    7
19.0    4
3.0     4
16.0    1
Name: 820, dtype: int64
10.0    15
7.0      1
Name: 821, dtype: int64
10.0    14
9.0      1
4.0      1
Name: 822, dtype: int64
12.0    10
13.0     3
10.0     2
5.0      1
Name: 823, dtype: int64
16.0    5
8.0     4
4.0     3
7.0     3
11.0    1
Name: 824, dtype: int64
16.0    5
4.0     3
13.0    3
10.0    3
12.0    2
Name: 825, dtype: int64
4.0    16
Name: 826, dtype: int64
4.0    16
Name: 827, dtype: int64
4.0     15
19.0     1
Name: 828, dtype: int64

4.0     14
12.0     1
3.0      1
Name: 829, dtype: int64
9.0     12
8.0      2
11.0     1
4.0      1
Name: 830, dtype: int64
4.0    16
Name: 831, dtype: int64
4.0     15
13.0     1
Name: 832, dtype: int64
4.0    16
Name: 833, dtype: int64
12.0    11
4.0      3
8.0      1
5.0      1
Name: 834, dtype: int64
10.0    15
11.0     1
Name: 835, dtype: int64
11.0    8
10.0    4
3.0     3
4.0     1
Name: 836, dtype: int64
11.0    8
4.0     7
8.0     1
Name: 837, dtype: int64
16.0    8
4.0     6
10.0    1
11.0    1
Name: 838, dtype: int64
4.0    16
Name: 839, dtype: int64
4.0     11
16.0     5
Name: 840, dtype: int64
10.0    15
12.0     1
Name: 841, dtype: int64
4.0    16
Name: 842, dtype: int64
9.0    16
Name: 843, dtype: int64
4.0    16
Name: 844, dtype: int64
4.0    16
Name: 845, dtype: int64
12.0    5
4.0     4
13.0    4
10.0    2
17.0    1
Name: 846, dtype: int64
9.0    14
4.0     2
Name: 847, dtype: int64
4.0    13
8.0     3
Name: 848, dtype: int64
12.0    13
10.0     2
3.0      1
Name: 849, dtype: int64
4.0     15
13.0     1
Name: 850, dtype: int64
4.0     12
10.0     2
11.0     2
Name: 851, dtype: int64
10.0    6
4.0     6
11.0    4
Name: 852, dtype: int64
7.0     11
16.0     5
Name: 853, dtype: int64
4.0     12
13.0     4
Name: 854, dtype: int64
4.0    16
Name: 855, dtype: int64
10.0    8
3.0     5
11.0    3
Name: 856, dtype: int64
10.0    16
Name: 857, dtype: int64
4.0     8
5.0     6
10.0    1
8.0     1
Name: 858, dtype: int64
4.0     14
13.0     2
Name: 859, dtype: int64
4.0    16
Name: 860, dtype: int64
12.0    16
Name: 861, dtype: int64
4.0    16
Name: 862, dtype: int64
4.0     8
7.0     3
3.0     2
16.0    2
10.0    1
Name: 863, dtype: int64
4.0     15
13.0     1
Name: 864, dtype: int64
10.0    16
Name: 865, dtype: int64
4.0    16
Name: 866, dtype: int64
10.0    8
4.0     3
7.0     3
6.0     1
19.0    1
Name: 867, dtype: int64
4.0    16
Name: 868, dtype: int64
4.0    16
Name: 869, dtype: int64
4.0     14
12.0     1
10.0     1
Name: 870, dtype: int64
4.0     13
13.0     3
Name: 871, dtype: int64
10.0    10
12.0     6
Name: 872, dtype: int64
4.0    16
Name: 873, dtype: int64
4.0     14
13.0     2
Name: 874, dtype: int64
3.0    14
7.0     1
8.0     1
Name: 875, dtype: int64
4.0     5
7.0     4
8.0     4
19.0    2
14.0    1
Name: 876, dtype: int64
4.0    16
Name: 877, dtype: int64
4.0    16
Name: 878, dtype: int64
8.0     13
7.0      2
14.0     1
Name: 879, dtype: int64
4.0    16
Name: 880, dtype: int64
4.0     10
13.0     6
Name: 881, dtype: int64
4.0    16
Name: 882, dtype: int64
4.0     6
19.0    5
7.0     3
3.0     1
10.0    1
Name: 883, dtype: int64
9.0    16
Name: 884, dtype: int64
14.0    13
8.0      2
13.0     1
Name: 885, dtype: int64
16.0    9
10.0    3
12.0    2
7.0     1
11.0    1
Name: 886, dtype: int64
10.0    16
Name: 887, dtype: int64
10.0    11
7.0      4
4.0      1
Name: 888, dtype: int64
9.0    16
Name: 889, dtype: int64
3.0    16
Name: 890, dtype: int64
12.0    15
3.0      1
Name: 891, dtype: int64
4.0    16
Name: 892, dtype: int64
4.0    16
Name: 893, dtype: int64
4.0    16
Name: 894, dtype: int64
3.0     9
7.0     4
14.0    2
4.0     1
Name: 895, dtype: int64
9.0    16
Name: 896, dtype: int64
4.0     9
3.0     4
2.0     1
11.0    1
10.0    1
Name: 897, dtype: int64
12.0    10
7.0      2
16.0     2
4.0      1
3.0      1
Name: 898, dtype: int64
3.0    9
4.0    7
Name: 899, dtype: int64
4.0    16
Name: 900, dtype: int64
16.0    15
21.0     1
Name: 901, dtype: int64
6.0    11
4.0     4
5.0     1
Name: 902, dtype: int64
12.0    16
Name: 903, dtype: int64
4.0    16
Name: 904, dtype: int64
4.0    14
7.0     2
Name: 905, dtype: int64
4.0     11
13.0     5
Name: 906, dtype: int64
4.0     12
11.0     2
12.0     1
13.0     1
Name: 907, dtype: int64
4.0    16
Name: 908, dtype: int64
4.0    16
Name: 909, dtype: int64
10.0    13
7.0      3
Name: 910, dtype: int64
9.0    9
4.0    7
Name: 911, dtype: int64
12.0    11
3.0      5
Name: 912, dtype: int64
4.0     7
13.0    5
12.0    3
10.0    1
Name: 913, dtype: int64
4.0     14
13.0     2
Name: 914, dtype: int64
4.0    16
Name: 915, dtype: int64
4.0     11
6.0      3
13.0     2
Name: 916, dtype: int64
9.0    7
8.0    6
4.0    2
5.0    1
Name: 917, dtype: int64
4.0    16
Name: 918, dtype: int64
16.0    13
8.0      2
7.0      1
Name: 919, dtype: int64
13.0    9
4.0     7
Name: 920, dtype: int64
4.0    16
Name: 921, dtype: int64
9.0    16
Name: 922, dtype: int64
4.0     12
13.0     2
12.0     2
Name: 923, dtype: int64
4.0    16
Name: 924, dtype: int64
10.0    13
16.0     3
Name: 925, dtype: int64
4.0     13
13.0     3
Name: 926, dtype: int64
9.0    16
Name: 927, dtype: int64
3.0     14
11.0     1
7.0      1
Name: 928, dtype: int64
4.0    15
5.0     1
Name: 929, dtype: int64
5.0    16
Name: 930, dtype: int64
19.0    11
4.0      3
5.0      2
Name: 931, dtype: int64
2.0     8
14.0    7
3.0     1
Name: 932, dtype: int64
3.0     8
7.0     5
10.0    1
8.0     1
4.0     1
Name: 933, dtype: int64
10.0    15
16.0     1
Name: 934, dtype: int64
7.0     7
10.0    7
16.0    1
19.0    1
Name: 935, dtype: int64
7.0     11
10.0     3
3.0      2
Name: 936, dtype: int64
12.0    13
14.0     3
Name: 937, dtype: int64
4.0    16
Name: 938, dtype: int64

In [23]:
pred['final']=pd.Series(final)
pred

,0,1,6,7,15,42,70,80,96,99,154,482,666,854,123456,123465,final
0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,12.0,12.0,12.0,12.0,12.0,12.0,13.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
2,12.0,12.0,16.0,7.0,10.0,12.0,16.0,7.0,16.0,16.0,10.0,10.0,16.0,12.0,12.0,10.0,16.0
3,7.0,7.0,3.0,3.0,7.0,3.0,3.0,3.0,16.0,7.0,7.0,3.0,7.0,3.0,7.0,3.0,3.0
4,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,10.0,10.0,10.0,10.0,10.0,16.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
935,10.0,7.0,7.0,7.0,7.0,19.0,7.0,10.0,7.0,10.0,16.0,10.0,7.0,10.0,10.0,10.0,7.0
936,7.0,10.0,7.0,7.0,7.0,3.0,7.0,10.0,7.0,7.0,7.0,7.0,3.0,7.0,7.0,10.0,7.0
937,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,14.0,14.0,14.0,12.0,12.0,12.0,12.0
938,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

In [24]:
pd.Series(pred['final']).to_csv('preds/final_fastai.csv', index=False, header=['Culture'])